function [H,C,G] = fcn_dynamics_2_link(in1,in2,in3)
%FCN_DYNAMICS_2_LINK
%    [H,C,G] = FCN_DYNAMICS_2_LINK(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    16-Aug-2025 16:07:57

J1 = in3(7,:);
J2 = in3(8,:);
M1 = in3(5,:);
M2 = in3(6,:);
dq1 = in2(1,:);
dq2 = in2(2,:);
l1 = in3(1,:);
l2 = in3(2,:);
q1 = in1(1,:);
q2 = in1(2,:);
r1 = in3(3,:);
r2 = in3(4,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q2);
t5 = q1+q2;
t6 = l1.^2;
t7 = l2.^2;
t8 = r2.^2;
t9 = cos(t5);
t10 = M2.*l1.*l2.*r2.*t3;
t11 = M2.*t7.*t8;
t12 = J2+t10+t11;
H = reshape([J1+t10+t12+M2.*t6+M1.*r1.^2.*t6,t12,t12,J2+t11],[2,2]);
if nargout > 1
    C = reshape([-M2.*dq2.*l1.*l2.*r2.*t4,M2.*dq1.*l1.*l2.*r2.*t4,-M2.*l1.*l2.*r2.*t4.*(dq1+dq2),0.0],[2,2]);
end
if nargout > 2
    G = [M2.*(l1.*t2+l2.*r2.*t9).*(9.81e+2./1.0e+2)+M1.*l1.*r1.*t2.*(9.81e+2./1.0e+2);M2.*l2.*r2.*t9.*(9.81e+2./1.0e+2)];
end
end
