function [p_ee,v_ee,J_ee,dJdq_ee,chain] = fcn_FK_2_link(in1,in2,in3)
%fcn_FK_2_link
%    [P_EE,V_EE,J_ee,dJdq_ee,CHAIN] = fcn_FK_2_link(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    16-Aug-2025 16:07:56

dq1 = in2(1,:);
dq2 = in2(2,:);
l1 = in3(1,:);
l2 = in3(2,:);
q1 = in1(1,:);
q2 = in1(2,:);
t2 = cos(q1);
t3 = sin(q1);
t4 = dq1+dq2;
t5 = q1+q2;
t6 = l1.*t2;
t7 = cos(t5);
t8 = l1.*t3;
t9 = sin(t5);
t10 = l2.*t7;
t11 = l2.*t9;
t12 = dq2.*t10;
t13 = dq2.*t11;
t14 = -t11;
t15 = t6+t10;
t16 = t8+t11;
p_ee = [t15;t16];
if nargout > 1
    t17 = dq1.*t15;
    t18 = dq1.*t16;
    t19 = t12+t17;
    v_ee = [-t13-t18;t19];
end
if nargout > 2
    J_ee = reshape([-t8+t14,t15,t14,t10],[2,2]);
end
if nargout > 3
    dJdq_ee = [-dq1.*t19-t4.*t12;-dq1.*(t13+t18)-t4.*t13];
end
if nargout > 4
    chain = reshape([0.0,0.0,t6,t8,t15,t16],[2,3]);
end
end
